import type { EmailTemplate, Newsletter } from './newsletters';

const image = (name: string) => `https://ysabelsociety.com/assets/${encodeURIComponent(name)}`;
const photography = [image('about-1.png'), image('asian-asian.png'), image('6I9A0496.png'), image('asian good 6I9A0405 (1).png'), image('about-3.png'), image('main2.png')];
type Direction = { id: string; name: string; description: string; layout: string; paper: string; ink: string; accent: string; dark?: boolean; order: number[]; subject: string; heading: string; eyebrow: string; body: string; second: string; story: string; detail: string; cta: string; sections: {title:string;body:string}[] };
const directions: Direction[] = [
  {id:'asian-nocturne',name:'Nocturne',description:'Dinner invitation · Black, gold & panoramic chapters',layout:'asian-nocturne',paper:'#080f10',ink:'#f2ead9',accent:'#baa366',dark:true,order:[0,4,2,1],subject:'After dark, a table at Ysabel Asian',heading:'An evening\nbeyond the ordinary.',eyebrow:'DINNER / AFTER DARK',body:'Let the city fall quiet for a moment. A table is waiting, the first glass is poured, and the kitchen is preparing an evening worth slowing down for.',second:'Begin with something unexpected.',story:'Delicate bites, a little heat, and a generous table. Discover the kitchen one plate at a time, with room for another conversation between courses.',detail:'Friday · 20:00 until late',cta:'Reserve your evening',sections:[{title:'The opening note',body:'Start with a selection to share. Ask our team to guide you through the evening’s flavours.'},{title:'One last glass',body:'Stay for a carefully mixed cocktail. There is no need to rush the end of a good evening.'}]},
  {id:'asian-ritual',name:'The Quiet Ritual',description:'A slow Sunday · Narrow imagery, pauses & rice paper',layout:'asian-ritual',paper:'#f2ecde',ink:'#383329',accent:'#786848',order:[4,0,1],subject:'A quieter Sunday at Ysabel Asian',heading:'Less hurry.\nMore flavour.',eyebrow:'SUNDAY / A SLOWER TABLE',body:'Leave the afternoon unplanned. Come for a thoughtful meal, a little stillness, and the kind of conversation that only happens when nobody is watching the clock.',second:'Small details. Lasting impressions.',story:'A balanced bite. A warm welcome. The pause before the next course. This Sunday, let the simplest moments become the ones you remember.',detail:'Sunday lunch · From 13:00',cta:'Find your table',sections:[{title:'Make space',body:'Choose a table for two or gather a few familiar faces. We will take care of the rest.'},{title:'Stay a little longer',body:'Finish with something sweet and let the afternoon find its own pace.'}]},
  {id:'asian-vermilion',name:'The Vermilion Invitation',description:'Promotional offer · Red typography & three-part menu',layout:'asian-vermilion',paper:'#fff9eb',ink:'#a72924',accent:'#b23229',order:[0,2,4,1],subject:'Your midweek invitation — a little extra from us',heading:'A little more\nto look forward to.',eyebrow:'MIDWEEK / SOCIETY INVITATION',body:'Make an occasion of Wednesday. Reserve our sharing menu for two and let the first welcome drink be on us. Good company is the only other ingredient you need.',second:'Two seats. A generous table.',story:'Explore a selection of kitchen favourites, thoughtfully paced for an evening together. This invitation is for those who believe a weekday can feel like a celebration.',detail:'Wednesday · 18:00–21:00 · Demo offer',cta:'Discover the offer',sections:[{title:'The invitation',body:'A sharing menu for two, accompanied by two welcome drinks. Replace this sample with your confirmed offer.'},{title:'Before you reserve',body:'Demo terms: advance reservation required, subject to availability, not combined with other offers. Confirm all dates and conditions before sending.'}]},
  {id:'asian-chef',name:'At the Chef’s Hand',description:'Kitchen portrait · Asymmetric editorial & six-image study',layout:'asian-chef',paper:'#f8f8f3',ink:'#242622',accent:'#6b7064',order:[0,4,3,2,1,5],subject:'A closer look inside the Ysabel Asian kitchen',heading:'The thought\nbehind the plate.',eyebrow:'FROM THE KITCHEN / ISSUE 01',body:'Before a dish reaches your table, there is a conversation between ingredients, technique and instinct. This month, we invite you a little closer to that process.',second:'Precision, with room for imagination.',story:'Our kitchen looks for the point where texture, temperature and flavour meet. Each plate begins with a question: what makes this ingredient worth paying attention to?',detail:'Kitchen stories · September edition',cta:'Explore the kitchen',sections:[{title:'A study in balance',body:'Something crisp beside something soft. Freshness against depth. Details that quietly change the whole experience.'},{title:'From preparation to service',body:'A final adjustment. A considered garnish. The moment when the kitchen’s work becomes your evening.'},{title:'Taste the story',body:'Join us and ask what the kitchen is especially excited to prepare this week.'}]},
  {id:'asian-listening',name:'The Listening Room',description:'DJ evening · Ink-blue programme & rhythmic image breaks',layout:'asian-listening',paper:'#101820',ink:'#eef0e6',accent:'#a9bccc',dark:true,order:[3,1,2,5],subject:'Friday: dinner, a guest DJ, and one more track',heading:'Come for dinner.\nStay for the next track.',eyebrow:'YSABEL ASIAN / THE LISTENING ROOM',body:'An evening that moves from the first plate to the last record. Settle in early, order something to share, and let our guest DJ take it from there.',second:'A soundtrack for staying.',story:'Warm selections, familiar favourites and a few discoveries. Bring the person whose music taste you trust — and the one you would like to surprise.',detail:'Friday · Dinner 19:00 · Guest DJ 21:00',cta:'Reserve a table',sections:[{title:'19:00 — Take your seat',body:'Arrive for dinner and a first drink. Let the evening begin without a hurry.'},{title:'21:00 — Guest DJ: Demo Artist',body:'An open-format selection for an intimate room. Replace this sample artist and schedule before sending.'},{title:'Late — Just one more',body:'A final cocktail, a favourite track, and the company you came for.'}]},
  {id:'asian-cocktail',name:'The Cocktail Atlas',description:'Bar journal · Numbered pairings & alternating columns',layout:'asian-cocktail',paper:'#eee7d9',ink:'#442226',accent:'#6e3037',order:[2,3,0,5,4],subject:'Three ways to begin your evening',heading:'First,\na cocktail.',eyebrow:'THE BAR JOURNAL / VOL. 01',body:'Citrus. Warmth. A surprising finish. Discover a few of the moods our bar is exploring this month — each one a different way into the evening.',second:'Find your first note.',story:'Tell us what you enjoy. Bright and refreshing, softly spiced, or something with a little more depth. Our team will help you choose.',detail:'Cocktail evenings · From 18:00',cta:'Meet us at the bar',sections:[{title:'01 / Bright beginnings',body:'A citrus-led serve, a fresh garnish and a clean finish. Sample concept: replace with your featured cocktail.'},{title:'02 / A little warmth',body:'Gentle spice, a savoury bite, and a conversation that carries on. Discover a pairing from the kitchen.'},{title:'03 / The final note',body:'Something deeper to close the evening. Ask the bar team for their current favourite.'}]},
  {id:'asian-season',name:'A Season at the Table',description:'Seasonal menu · Numbered courses & botanical restraint',layout:'asian-season',paper:'#f3f3e9',ink:'#2b3d31',accent:'#617653',order:[0,4,1,2],subject:'A new season, thoughtfully served',heading:'The season,\nin a few considered plates.',eyebrow:'SEASONAL NOTES / THE TASTING TABLE',body:'A change in the air is a good reason to gather. Discover a seasonal selection shaped around freshness, contrast and the pleasure of sharing something new.',second:'Follow the kitchen’s lead.',story:'Begin lightly, discover a little warmth, and leave room for a final surprise. Every course has its own place in the conversation.',detail:'Seasonal tasting concept · Selected evenings',cta:'View the seasonal invitation',sections:[{title:'01 / To begin',body:'Fresh, delicate opening bites. Replace this sample with your confirmed first course.'},{title:'02 / At the heart',body:'Warmth, depth and something to share. Add your seasonal main-course description here.'},{title:'03 / To linger',body:'A gently sweet finish and one last conversation. Complete the menu with your dessert.'}]},
  {id:'asian-private',name:'Behind the Screen',description:'Private dining · Framed invitation & intimate diptych',layout:'asian-private',paper:'#272126',ink:'#f4eadb',accent:'#c3a18b',dark:true,order:[4,1,3],subject:'An evening, entirely yours',heading:'A table\nfor your people.',eyebrow:'PRIVATE DINING / BY INVITATION',body:'A birthday, a reunion, an occasion that belongs to you. Let us help shape an intimate evening around good food and the people you want beside you.',second:'Consider every detail.',story:'From the first welcome to the final course, we can discuss the rhythm of your celebration. Tell us what you have in mind and we will begin there.',detail:'Private gatherings · By arrangement',cta:'Enquire about your evening',sections:[{title:'Made for gathering',body:'A considered menu, a comfortable setting, and space to enjoy your guests. Group size and availability are confirmed on enquiry.'},{title:'Begin with a conversation',body:'Share your preferred date, number of guests and any dietary requirements with our reservations team.'}]},
  {id:'asian-lunch',name:'The Lunch Edition',description:'Lunch promotion · Newspaper masthead & compact photo grid',layout:'asian-lunch',paper:'#ffffff',ink:'#24333d',accent:'#536e7e',order:[1,0,4,3,2,5],subject:'Your lunch break deserves a better setting',heading:'A good afternoon\nstarts at the table.',eyebrow:'THE LUNCH EDITION',body:'Step away from the usual. Join us for a thoughtful lunch with colleagues, a familiar friend, or simply a little time to yourself.',second:'A shorter pause. A better day.',story:'A welcoming room and a carefully prepared meal can change the shape of an afternoon. Come with an appetite; leave with something to talk about.',detail:'Weekday lunch · 12:00–15:00 · Demo schedule',cta:'Make a lunch reservation',sections:[{title:'The midday selection',body:'Sample promotion: two courses and a soft drink. Add your confirmed menu, price and dates before sending.'},{title:'For the table',body:'Choose a few plates to share, or keep your lunch entirely your own.'},{title:'Back to the day',body:'Let us know if you are on a schedule when you arrive. We will help you plan your meal.'}]},
  {id:'asian-midnight',name:'Midnight Society',description:'Late-night invitation · Oversized type & cinematic contact sheet',layout:'asian-midnight',paper:'#080909',ink:'#ded8c4',accent:'#bfa65d',dark:true,order:[5,2,3,1,0],subject:'The evening is not over yet',heading:'NOT QUITE\nREADY TO\nGO HOME.',eyebrow:'MIDNIGHT SOCIETY / AFTER HOURS',body:'For the conversations that deserve another hour. For the friend you have not seen in too long. Meet us for a late drink and see where the evening goes.',second:'Your last stop. Our warmest welcome.',story:'Low light, good company and something delicious from the bar. There is a certain kind of evening that only begins when the city slows down.',detail:'Saturday · Late-night concept · Confirm hours',cta:'Plan your late evening',sections:[{title:'A seat at the bar',body:'Begin with a familiar favourite or let the team introduce you to something new.'},{title:'Something to share',body:'A few thoughtful bites make room for one more conversation. Confirm late-kitchen availability before sending.'},{title:'See you after dark',body:'Bring your people. We will be happy to see you.'}]},
];
export const asianTemplates: EmailTemplate[] = directions.map(d=>({id:d.id,name:d.name,venue:'Ysabel Asian',description:d.description,layout:d.layout,paper:d.paper,ink:d.ink,accent:d.accent,dark:d.dark}));
export function asianDefaults(id:string): Partial<Newsletter> {
  const d=directions.find(d=>d.id===id); if(!d)return {};
  return {subject:d.subject,preheader:d.body,heading:d.heading,eyebrow:d.eyebrow,body:d.body,secondaryHeading:d.second,secondaryBody:d.story,detail:d.detail,cta:d.cta,images:d.order.map(i=>photography[i]),alts:d.order.map(i=>['Ysabel Asian sushi','Ysabel Asian dining room','Ysabel cocktail','Ysabel Asian bar','A table at Ysabel Asian','Ysabel bar after dark'][i]),sections:d.sections.map(s=>({...s})),font:d.id==='asian-midnight'||d.id==='asian-listening'?'modern':'editorial'};
}

export function renderAsianBody(d:Newsletter,t:EmailTemplate,urls:string[],escape:(s:string)=>string,safe:(s:string)=>string): string {
  const text=(s:string)=>escape(s).replace(/\n/g,'<br>');
  const serif=d.font==='modern'?'Arial,Helvetica,sans-serif':d.font==='classic'?'Times New Roman,Times,serif':'Georgia,Times,serif';
  const table=(rows:string)=>`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;border-collapse:collapse;table-layout:fixed;">${rows}</table>`;
  const row=(s:string,pad='0',bg=t.paper,ink=t.ink)=>`<tr><td class="asian-pad" bgcolor="${bg}" style="padding:${pad};background:${bg};color:${ink};">${s}</td></tr>`;
  const copy=(s:string,color=t.ink)=>`<p style="font:16px/1.85 Arial,Helvetica,sans-serif;color:${color};margin:0 0 24px;">${text(s)}</p>`;
  const title=(s:string,size=34,color=t.ink)=>`<h2 style="font:normal ${size}px/1.15 ${serif};color:${color};margin:0 0 24px;">${text(s)}</h2>`;
  const label=(s:string,color=t.accent)=>`<p style="font:12px/1.7 Arial,Helvetica,sans-serif;letter-spacing:2px;color:${color};margin:0 0 20px;">${text(s)}</p>`;
  const heading=label(d.eyebrow)+`<h1 style="font:normal ${t.layout==='asian-midnight'?72:54}px/1.04 ${serif};letter-spacing:-1.5px;color:${t.ink};margin:0 0 30px;">${text(d.heading)}</h1>`;
  const used=new Set<number>();
  const photo=(i:number,width=640)=>{if(!urls[i])return '';used.add(i);return `<img src="${escape(safe(urls[i]))}" alt="${escape(d.alts[i]||d.venue)}" width="${width}" style="display:block;width:100%;max-width:${width}px;height:auto;border:0;">`;};
  const pair=(a:string,b:string,ratio=50)=>table(`<tr><td class="stack" width="${ratio}%" valign="top" style="width:${ratio}%;padding:10px;">${a}</td><td class="stack" width="${100-ratio}%" valign="middle" style="width:${100-ratio}%;padding:10px;">${b}</td></tr>`);
  const section=(i:number,fallbackTitle=d.secondaryHeading,fallbackBody=d.secondaryBody)=>title(d.sections?.[i]?.title||fallbackTitle,28)+copy(d.sections?.[i]?.body||fallbackBody);
  const rule=`<hr style="border:0;border-top:1px solid ${t.accent};margin:26px 0;">`;
  let html='';
  switch(t.layout){
    case 'asian-nocturne': html=row(photo(0))+row(heading,'54px 56px 20px')+row(pair(label('01 / THE TABLE')+copy(d.body),photo(1),42),'0 32px 44px')+row(title(d.secondaryHeading,34,'#191b16')+copy(d.secondaryBody,'#191b16'),'48px 56px','#eae2cf','#191b16')+row(pair(photo(2),section(0)),'32px')+row(photo(3))+row(section(1),'52px 64px');break;
    case 'asian-ritual': html=row(photo(0))+row(label('○   /   YSABEL ASIAN')+heading,'72px 72px 20px')+row(copy(d.body),'0 88px 44px')+row(table(row(photo(1,360),'0 70px')),'0 44px 48px')+row(rule+title(d.secondaryHeading)+copy(d.secondaryBody),'0 72px 56px')+row(photo(2))+row(section(0)+rule+section(1),'64px 80px');break;
    case 'asian-vermilion': html=row(label('AN INVITATION FROM YSABEL ASIAN')+heading+rule,'52px 44px 20px')+row(copy(d.body),'0 44px 32px')+row(table(`<tr>${[0,1,2].map(i=>`<td width="33%" valign="top" style="padding:5px;">${photo(i,200)}${label(String(i+1).padStart(2,'0'))}</td>`).join('')}</tr>`),'0 20px')+row(title(d.secondaryHeading,42)+copy(d.secondaryBody),'52px 44px')+row(pair(section(0),section(1)),'16px 30px')+row(photo(3));break;
    case 'asian-chef': html=row(pair(photo(0),heading+label('A KITCHEN STUDY'),52),'0 18px')+row(pair(photo(1)+label('I / FLAVOUR'),copy(d.body)+photo(2),44),'20px 30px')+row(title(d.secondaryHeading,46)+copy(d.secondaryBody),'52px 64px')+row(pair(section(0),photo(3),42),'0 30px 34px')+row(pair(photo(4),photo(5)),'0 22px')+row(section(1)+rule+section(2),'48px 64px');break;
    case 'asian-listening': html=row(heading+rule+label(d.detail),'50px 42px 24px')+row(photo(0))+row(copy(d.body),'44px 54px 16px')+row(table([0,1,2].map(i=>row(label('0'+(i+1))+section(i),'28px 34px',i%2?'#22313c':t.paper)).join('')),'0 22px 44px')+row(pair(photo(1),photo(2)),'0 18px')+row(title(d.secondaryHeading)+copy(d.secondaryBody),'48px 54px')+row(photo(3));break;
    case 'asian-cocktail': html=row(heading+rule+copy(d.body),'56px 46px 24px')+row(pair(photo(0),section(0),54),'0 24px 38px')+row(pair(section(1),photo(1),44),'0 24px 38px')+row(pair(photo(2),section(2),54),'0 24px 38px')+row(title(d.secondaryHeading,44)+copy(d.secondaryBody),'48px 54px','#ded2bd')+row(pair(photo(3),photo(4)),'28px 20px');break;
    case 'asian-season': html=row(label('YSABEL ASIAN / SEASONAL JOURNAL')+heading+copy(d.body),'54px 54px 24px')+row(photo(0))+row(table([0,1,2].map(i=>row(pair(`<span style="font:52px Georgia;color:${t.accent};">0${i+1}</span>`,section(i),20)+rule,'20px 0')).join('')),'38px 52px 16px')+row(pair(photo(1),photo(2)),'0 22px')+row(title(d.secondaryHeading)+copy(d.secondaryBody),'50px 56px')+row(photo(3));break;
    case 'asian-private': html=row(`<div style="border:1px solid ${t.accent};padding:42px 24px;text-align:center;">${label('○')}${heading}${copy(d.body)}</div>`,'30px')+row(pair(photo(0),photo(1)),'18px 16px')+row(title(d.secondaryHeading,42)+copy(d.secondaryBody),'54px 64px')+row(rule+section(0)+rule+section(1),'0 64px 46px')+row(photo(2));break;
    case 'asian-lunch': html=row(label(d.eyebrow)+rule+heading+label(d.detail),'32px 34px 10px')+row(photo(0))+row(pair(copy(d.body),section(0)),'28px 24px')+row(pair(photo(1),photo(2)),'0 18px')+row(title(d.secondaryHeading,42),'38px 42px 0')+row(pair(copy(d.secondaryBody)+photo(3),section(1)+photo(4)),'0 24px 30px')+row(photo(5))+row(section(2),'40px 48px');break;
    case 'asian-midnight': html=row(heading+label(d.detail),'50px 32px 30px')+row(photo(0))+row(copy(d.body),'44px 50px')+row(pair(photo(1),photo(2),35),'0 10px')+row(title(d.secondaryHeading,48)+copy(d.secondaryBody),'60px 44px 30px')+row(pair(photo(3),section(0),60),'0 24px 42px')+row(photo(4))+row(section(1)+rule+section(2),'50px 54px');break;
  }
  // Extra slots remain part of the newsletter rather than disappearing in a fixed template.
  const extras=urls.map((_,i)=>i).filter(i=>!used.has(i));
  if(extras.length)html+=row(rule+label('MORE FROM YSABEL ASIAN'),'24px 44px 0')+extras.map(i=>row(photo(i),'16px 44px')).join('');
  return html;
}
