import { asianTemplates, asianDefaults, renderAsianBody } from './asian-newsletters';
export const venues = ['Ysabel Garden', 'Ysabel Italian', 'Ysabel Asian'] as const;
export type Venue = typeof venues[number];
export type Newsletter = { id: string; name: string; venue: Venue; template: string; subject: string; preheader: string; eyebrow: string; heading: string; body: string; secondaryHeading: string; secondaryBody: string; detail: string; cta: string; link: string; address: string; unsubscribe: string; images: string[]; alts: string[]; font: 'editorial' | 'classic' | 'modern'; updatedAt?: number; sections?: { title: string; body: string }[] };
export type EmailTemplate = { id: string; venue: Venue; name: string; description: string; layout: string; paper: string; ink: string; accent: string; dark?: boolean };
export const emailTemplates: EmailTemplate[] = [
  { id: 'garden-journal', venue: 'Ysabel Garden', name: 'The Garden Journal', description: 'Botanical green · Full-width photography', layout: 'hero', paper: '#f4f3ea', ink: '#293b2c', accent: '#4c613e' },
  { id: 'garden-gathering', venue: 'Ysabel Garden', name: 'An Open Invitation', description: 'White space · Intimate letter', layout: 'letter', paper: '#ffffff', ink: '#26312b', accent: '#405c47' },
  { id: 'garden-evening', venue: 'Ysabel Garden', name: 'After Sundown', description: 'Deep forest · Two photographic moments', layout: 'diptych', paper: '#172d25', ink: '#f5f1e6', accent: '#bec9a3', dark: true },
  { id: 'italian-table', venue: 'Ysabel Italian', name: 'La Tavola', description: 'Ivory & terracotta · Split editorial', layout: 'split', paper: '#fffaf1', ink: '#442d23', accent: '#a4442e' },
  { id: 'italian-menu', venue: 'Ysabel Italian', name: 'The Seasonal Table', description: 'Cream paper · Menu-led invitation', layout: 'menu', paper: '#f4eedc', ink: '#3c3425', accent: '#71603f' },
  { id: 'italian-stories', venue: 'Ysabel Italian', name: 'Stories from the Kitchen', description: 'Gallery triptych · Restrained typography', layout: 'gallery', paper: '#ffffff', ink: '#302f2b', accent: '#666b4a' },
  ...asianTemplates,
];
export const defaultPhotography: Record<Venue, string[]> = {
  'Ysabel Garden': ['https://ysabelsociety.com/assets/ysabel-2.png', 'https://ysabelsociety.com/assets/ysabel-3.png', 'https://ysabelsociety.com/assets/about-1.png'],
  'Ysabel Italian': ['https://ysabelsociety.com/assets/good%20IMG_7834.png', 'https://ysabelsociety.com/assets/ysabel-1.png', 'https://ysabelsociety.com/assets/about-2.png'],
  'Ysabel Asian': ['https://ysabelsociety.com/assets/6I9A0496.png', 'https://ysabelsociety.com/assets/asian-asian.png', 'https://ysabelsociety.com/assets/about-3.png'],
};
export function createNewsletter(template: EmailTemplate): Newsletter {
  const asian = template.venue === 'Ysabel Asian', italian = template.venue === 'Ysabel Italian';
  return { id: crypto.randomUUID(), name: template.name, venue: template.venue, template: template.id, subject: `${template.venue} — an invitation to the table`, preheader: 'A new evening, a familiar welcome. Make time for something memorable.', eyebrow: 'A PERSONAL INVITATION', heading: asian ? 'Flavour. Fire.\nA little mystery.' : italian ? 'At the table,\ntogether.' : 'Where the evening\nfinds its rhythm.', body: asian ? 'Some evenings deserve your full attention. Discover a considered balance of texture, warmth and flavour at Ysabel Asian. Take your time. Let the next course surprise you.' : italian ? 'A generous table. A conversation that lasts. Join us at Ysabel Italian for the simple pleasure of good food, thoughtfully prepared and shared with the people you love.' : 'Step into the Garden. Settle into the evening, share something delicious and stay for the conversation. We would love to see you here.', secondaryHeading: asian ? 'A slower kind of discovery' : italian ? 'From our kitchen to your table' : 'Stay a little longer', secondaryBody: 'An invitation to make an occasion of the everyday. Discover what our team is preparing, and choose an evening to make your own.', detail: 'Lunch & dinner · Prishtina', cta: 'Discover & reserve', link: 'https://ysabelsociety.com/', address: '', unsubscribe: '*|UNSUB|*', images: [...defaultPhotography[template.venue]], alts: [`${template.venue} dining`, `${template.venue} atmosphere`, `${template.venue} detail`], font: 'editorial', ...asianDefaults(template.id) };
}
export function escapeEmail(value: string) { return String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!); }
export function safeEmailUrl(value: string, preview = false): string {
  if (!value.trim()) return '';
  try { const url = new URL(value, 'https://ysabelsociety.com'); if (!['https:', ...(preview ? ['blob:'] : [])].includes(url.protocol)) return ''; if (!preview && (url.searchParams.has('access_token') || url.pathname.startsWith('/contentpreview/api/media/'))) return ''; return url.href; } catch { return ''; }
}
export function renderNewsletter(d: Newsletter, imageUrls: string[], preview = false, test = false): string {
  const t = emailTemplates.find(t => t.id === d.template) || emailTemplates[0];
  const serif = d.font === 'modern' ? 'Arial, Helvetica, sans-serif' : d.font === 'classic' ? "'Times New Roman', Times, serif" : "Georgia, 'Times New Roman', serif";
  const text = (v: string) => escapeEmail(v).replace(/\n/g, '<br>');
  const table = (rows: string, width = '100%') => `<table role="presentation" width="${width}" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;width:${width === '100%' ? width : width + 'px'};">${rows}</table>`;
  const row = (content: string, padding = '0') => `<tr><td style="padding:${padding};">${content}</td></tr>`;
  const img = (index: number, width = 552) => { const url = safeEmailUrl(imageUrls[index] || '', preview); return url ? `<img src="${escapeEmail(url)}" alt="${escapeEmail(d.alts[index] || d.venue)}" width="${width}" border="0" style="display:block;width:100%;max-width:${width}px;height:auto;border:0;">` : `<p style="padding:50px 16px;border:1px solid ${t.accent};font:14px Arial;color:${t.ink};text-align:center;">Choose a photograph</p>`; };
  const eyebrow = `<p style="font:11px/1.7 Arial,Helvetica,sans-serif;letter-spacing:3px;color:${t.accent};margin:0 0 18px;">${text(d.eyebrow)}</p>`;
  const heading = `<h1 style="font-family:${serif};font-size:${t.layout === 'vermilion' ? 60 : 44}px;line-height:1.1;font-weight:normal;margin:0 0 24px;color:${t.ink};">${text(d.heading)}</h1>`;
  const paragraph = (value: string) => `<p style="font:16px/1.85 Arial,Helvetica,sans-serif;color:${t.ink};margin:0 0 20px;">${text(value)}</p>`;
  const secondary = `<h2 style="font-family:${serif};font-size:28px;line-height:1.25;font-weight:normal;color:${t.ink};margin:0 0 20px;">${text(d.secondaryHeading)}</h2>${paragraph(d.secondaryBody)}`;
  const intro = eyebrow + heading + paragraph(d.body);
  const split = (left: string, right: string) => table(`<tr><td class="stack" width="50%" valign="top" style="width:50%;padding:12px;">${left}</td><td class="stack" width="50%" valign="middle" style="width:50%;padding:12px;">${right}</td></tr>`);
  let body = '';
  switch (t.layout) {
    case 'hero': body = row(img(0, 640)) + row(intro, '44px') + row(split(img(1, 264), secondary), '0 32px 32px'); break;
    case 'letter': body = row(intro, '56px 64px 24px') + row(img(0), '0 44px') + row(secondary, '40px 64px'); break;
    case 'diptych': body = row(intro, '48px') + row(split(img(0, 264), img(1, 264)), '0 24px') + row(secondary, '40px 48px'); break;
    case 'split': body = row(split(img(0, 264), intro), '24px') + row(secondary, '24px 48px') + row(img(1), '0 44px 32px'); break;
    case 'menu': body = row(`<div style="text-align:center;">${intro}</div>`, '48px') + row(img(0), '0 44px') + row(`<div style="border-top:1px solid ${t.accent};border-bottom:1px solid ${t.accent};padding:32px 0;text-align:center;">${secondary}</div>`, '32px 60px'); break;
    case 'gallery': body = row(heading, '40px 44px 8px') + row(table(`<tr>${[0, 1, 2].map(i => `<td width="33%" valign="top" style="padding:4px;">${img(i, 176)}</td>`).join('')}</tr>`), '0 28px') + row(eyebrow + paragraph(d.body) + secondary, '40px 68px'); break;
    case 'nocturne': body = row(img(0, 640)) + row(intro, '48px 52px') + row(split(img(1, 264), secondary), '0 32px 40px'); break;
    case 'ritual': body = row(eyebrow + heading, '48px 64px 24px') + row(img(0), '0 44px') + row(paragraph(d.body), '36px 80px') + row(table(row(img(1, 320)), '320'), '0 44px 32px') + row(secondary, '16px 64px 32px'); break;
    case 'vermilion': body = row(intro, '56px 48px 24px') + row(img(0), '0 44px') + row(`<p style="border-top:1px solid ${t.accent};border-bottom:1px solid ${t.accent};padding:16px 0;font:11px/1.5 Arial;letter-spacing:3px;text-align:center;color:${t.ink};">TASTE &nbsp; / &nbsp; DISCOVER &nbsp; / &nbsp; GATHER</p>`, '20px 44px') + row(secondary, '28px 60px'); break;
  }
  if (t.layout.startsWith('asian-')) body = renderAsianBody(d, t, imageUrls, escapeEmail, v => safeEmailUrl(v, preview));
  if (test) body = row('<p style="font:12px Arial;text-align:center;padding:12px;color:#333;background:#eee;">DESIGN TEST — SAMPLE CONTENT. NOT A LIVE OFFER.</p>') + body;
  const unsubscribe = d.unsubscribe === '*|UNSUB|*' ? d.unsubscribe : safeEmailUrl(d.unsubscribe);
  const logo = `https://ysabelsociety.com/assets/ysabel-logo-${t.dark ? 'white' : 'black'}.png`;
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>${escapeEmail(d.subject)}</title><style>@media screen and (max-width:600px){.email-shell{width:100%!important;table-layout:fixed}.email-shell table{width:100%!important;max-width:100%!important;table-layout:fixed}.email-shell td{box-sizing:border-box}.stack{display:block!important;width:auto!important}.email-shell h1{font-size:36px!important}.email-shell td{word-break:normal} }</style></head><body style="margin:0;padding:0;background:#e7e7e2;"><div style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">${text(d.preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#e7e7e2"><tr><td align="center" style="padding:24px 0;"><!--[if mso]><table role="presentation" width="640"><tr><td><![endif]--><table role="presentation" class="email-shell" width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="${t.paper}" style="width:100%;max-width:640px;border-collapse:collapse;background:${t.paper};">${row(`<img src="${logo}" alt="Ysabel Society" width="98" style="display:block;width:98px;height:auto;margin:0 auto;"><p style="text-align:center;font:10px Arial;letter-spacing:3px;margin:16px 0 0;color:${t.ink};">${escapeEmail(d.venue.toUpperCase())}</p>`, '32px')}${body}${row(`<p style="font:12px/1.6 Arial;letter-spacing:1px;color:${t.ink};text-align:center;">${text(d.detail)}</p><table role="presentation" align="center" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" bgcolor="${t.accent}" style="padding:16px 28px;background:${t.accent};"><a href="${escapeEmail(safeEmailUrl(d.link) || 'https://ysabelsociety.com/')}" style="font:bold 14px Arial;color:${t.dark ? '#17231b' : '#ffffff'};text-decoration:none;display:inline-block;">${text(d.cta)}</a></td></tr></table>`, '8px 40px 48px')}${row(`<p style="font:12px/1.8 Arial;color:${t.ink};text-align:center;margin:0;">YSABEL SOCIETY<br>${text(d.address || '[Business postal address — replace before sending]')}<br>You are receiving this email because you subscribed to Ysabel Society.<br><a href="${escapeEmail(unsubscribe || '#')}" style="color:${t.ink};text-decoration:underline;">Unsubscribe</a> &nbsp; · &nbsp; <a href="https://ysabelsociety.com/" style="color:${t.ink};">Visit Ysabel</a></p>`, '28px 32px')}</table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>`;
}
export function newsletterText(d: Newsletter) { return [d.venue, d.heading, d.body, d.secondaryHeading, d.secondaryBody, ...(d.sections || []).flatMap(s => [s.title,s.body]), d.detail, `${d.cta}: ${d.link}`, d.address, `Unsubscribe: ${d.unsubscribe}`].join('\n\n'); }
